name: Regression testing - dev

on:
  workflow_dispatch:
     

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
           npm install -g pnpm
           pnpm install
        working-directory: ./server  

      - name: Run Jest tests
        id: jest-tests
        run: |
          pnpm test
          echo "exit-code=${?}" >> $GITHUB_ENV
        working-directory: ./server 
        continue-on-error: false

  smoke_testing:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run smoke tests
        working-directory: ./test-automation
        run: npm run smoke-testing-dev
        
      - name: Upload smoke test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: smoke-test-reports
          path: ./test-automation/cypress/reports

  api_testing:
    runs-on: ubuntu-latest
    needs: smoke_testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API tests
        working-directory: ./test-automation
        run: npm run api-tests-dev

      - name: Upload API test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-test-reports
          path: ./test-automation/cypress/reports

  e2e_testing:
    runs-on: ubuntu-latest
    needs: api_testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run E2E tests
        working-directory: ./test-automation
        run: npm run e2e-tests-dev:chrome
        
        
      - name: Upload E2E test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-reports
          path: ./test-automation/cypress/reports